import {Calendar} from './calendar-type';

export let calendars: Calendar[];
calendars = [
  {
    id: 0,
    limit: 2,
    heading: 'January',
    image: ['assets/images/static-slider/profiles/Screenshot_101.png', 'assets/images/static-slider/profiles/user2.jpg'],
    image2: ['assets/images/static-slider/profiles/Screenshot_101.png', 'assets/images/static-slider/profiles/user1.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg', 'assets/images/static-slider/profiles/user2.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg', 'assets/images/static-slider/profiles/Screenshot_101.png'],
    image5: [],
    subHeading: ['17 de Janeiro', '22 de Janeiro'],
    subHeading2: ['22 de Janeiro', '23 de Janeiro'],
    subHeading3: ['24 de Janeiro', '25 de Janeiro'],
    subHeading4: ['27 de Janeiro', '27 de Janeiro'],
    subHeading5: ['', ''],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Filipe Paixão', 'Carminda Batista'],
    blogDate2: ['Rúben Wilson', 'Gerson Abreu'],
    blogDate3: ['Tiago Monginho', 'Tiago Costa'],
    blogDate4: ['Diogo Porta-Nova', 'Maria Mendes'],
    blogDate5: ['', ''],
  },
  {
    id: 1,
    limit: 4,
    heading: 'February',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: [],
    // tslint:disable-next-line:max-line-length
    subHeading: ['4 de Fevereiro', '4 de Fevereiro', '7 de Fevereiro', '8 de Fevereiro'],
    subHeading2: ['9 de Fevereiro', '12 de Fevereiro', '13 de Fevereiro', '14 de Fevereiro'],
    subHeading3: ['14 de Fevereiro', '15 de Fevereiro', '16 de Fevereiro', '20 de Fevereiro'],
    subHeading4: ['22 de Fevereiro', '22 de Fevereiro', '26 de Fevereiro', '27 de Fevereiro'],
    subHeading5: [],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Odette Ribeiro Cardoso', 'Patrícia Bernardo', 'Luís Leandro', 'Ana Isabel Rodrigues'],
    blogDate2: ['Simão Townshend', 'Leonardo Ribeiro Silva', 'Pedro Grilo', 'Ana Paula Joaquim'],
    blogDate3: ['Inês Maria Veríssimo', 'Rui Patinho', 'Fernando Leão', 'Laurinda Fernandes'],
    blogDate4: ['Inês Alves', 'Fábio Macarrão', 'João Pedro Cardoso', 'Daniela Mendes'],
    blogDate5: [],
  },
  {
    id: 2,
    limit: 5,
    heading: 'March',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image5: ['assets/images/static-slider/profiles/user1.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['1 de Março', '2 de Março', '3 de Março', '4 de Março', '5 de Março'],
    subHeading2: ['6 de Março', '6 de Março', '6 de Março', '8 de Março', '10 de Março'],
    subHeading3: ['11 de Março', '17 de Março', '19 de Março', '20 de Março', '23 de Março'],
    subHeading4: ['24 de Março', '24 de Março', '27 de Março', '28 de Março', '31 de Março'],
    subHeading5: ['31 de Março'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Diogo Ferreira', 'Joana Lidónio', 'Rui Pires', 'João Neves', 'Nuno Cerdeira'],
    blogDate2: ['Gonçalo Correira', 'Duarte Almeida', 'Rodrigo Silva', 'Ana Catarina Salvador', 'Mariana Roque'],
    blogDate3: ['Rita Carriço', 'Jeff Soares', 'Miguel Portugal', 'Sofia Margarida', 'Carolina Montez'],
    blogDate4: ['João Pereira', 'João Pedro Salvador', 'Tiago Gil', 'João Francisco André', 'Gonçalo Cunha Calado'],
    blogDate5: ['Teresa Amaral'],
  },
  {
    id: 3,
    limit: 5,
    heading: 'April',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image5: ['assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['4 de Abril', '4 de Abril', '5 de Abril', '5 de Abril', '7 de Abril'],
    subHeading2: ['9 de Abril', '10 de Abril', '10 de Abril', '11 de Abril', '12 de Abril'],
    subHeading3: ['15 de Abril', '18 de Abril', '19 de Abril', '20 de Abril', '20 de Abril'],
    subHeading4: ['23 de Abril', '23 de Abril', '23 de Abril', '24 de Abril', '28 de Abril'],
    subHeading5: ['29 de Abril', '29 de Abril', '29 de Abril', '30 de Abril'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Miguel Correia', 'Marcelo Lopes', 'Rui Serrão', 'Diogo Ferreira Azoia', 'Vasco Barnabé'],
    blogDate2: ['Dinis Abreu', 'Elsa Maurício', 'Ana Barbosa', 'Bruna Ferreira', 'Ana Sofia Azoia'],
    blogDate3: ['Zé Eduardo', 'João Branquinho', 'Ermelinda Pitas', 'Rodrigo Vitorino', 'Laura Marta'],
    blogDate4: ['Error', 'Isabel Morais', 'Rita Veríssimo Farinha', 'Pedro Castelo', 'Sónia(Brave-Heart)'],
    blogDate5: ['Ludgero Teixeira', 'Henrique Raposo', 'Mariana Silva', 'Miguel Luís de Augusto'],
  },
  {
    id: 4,
    limit: 6,
    heading: 'May',
    image: ['assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image5: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['1 de Maio', '1 de Maio', '2 de Maio', '3 de Maio', '5 de Maio', '5 de Maio'],
    subHeading2: ['5 de Maio', '5 de Maio', '6 de Maio', '6 de Maio', '7 de Maio', '8 de Maio'],
    subHeading3: ['8 de Maio', '11 de Maio', '12 de Maio', '12 de Maio', '15 de Maio', '17 de Maio'],
    subHeading4: ['18 de Maio', '18 de Maio', '18 de Maio', '22 de Maio', '22 de Maio', '22 de Maio'],
    subHeading5: ['24 de Maio', '28 de Maio', '30 de Maio', '30 de Maio', '31 de Maio'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Mariana Salvador', 'Rita Alexandre', 'Patrícia Cardoso', 'Eduardo Santos', 'Mariana Domingos', 'Rodrigo Ramos'],
    blogDate2: ['Hélder Godinho', 'José Gomes', 'João Diogo Rosa', 'Mário Catarino', 'João Carlos Miranda' , 'Tomás Alves Silva'],
    blogDate3: ['Nuno Rolo', 'João Fulgêncio', 'Lucas Oliveira', 'Fátima Pereira', 'Raquel Ferreira', 'Nuno Fonseca'],
    blogDate4: ['Manuel Lourenço', 'Miguel Carvalho', 'Joana Carmo', 'Bernardo Marques', 'Francisco Miguel Carrilho', 'Jaybee Kieth Ronquilo'],
    blogDate5: ['Catarina Duarte', 'Ana Silvério', 'Eunice Minhoto', 'Miguel Maia', 'Jailson Varela'],
  },
  {
    id: 5,
    limit: 4,
    heading: 'June',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['5 de Junho', '6 de Junho', '6 de Junho', '9 de Junho'],
    subHeading2: ['10 de Junho', '13 de Junho', '14 de Junho', '15 de Junho'],
    subHeading3: ['16 de Junho', '17 de Junho', '18 de Junho', '19 de Junho'],
    subHeading4: ['19 de Junho', '19 de Junho', '20 de Junho', '21 de Junho'],
    subHeading5: ['22 de Junho', '22 de Junho', '27 de Junho', '28 de Junho'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Joana Escrevente', 'João Colaço', 'Miguel Horta', 'Luís Pereira'],
    blogDate2: ['André Duarte', 'Gonçalo Serrano', 'Guilherme Madeira', 'Denis Andrei'],
    blogDate3: ['Rui Miguel (Sr.Estudante)', 'Matilde Nogueira', 'João Queimado', 'João Branco'],
    blogDate4: ['Rui Miguel (Friend)', 'Beatriz Sá Pereira', 'Ana Roque', 'João Santos'],
    blogDate5: ['Chen Cheng', 'Maria Francisca Matos', 'Mónica Fonseca', 'Elsa Xênon Fkap'],
  },
  {
    id: 6,
    limit: 8,
    heading: 'July',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image5: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['2 de Julho', '4 de Julho', '4 de Julho', '6 de Julho', '6 de Julho', '9 de Julho', '9 de Julho', '10 de Julho'],
    subHeading2: ['10 de Julho', '13 de Julho', '13 de Julho', '14 de Julho', '14 de Julho', '14 de Julho', '16 de Julho', '16 de Julho'],
    subHeading3: ['17 de Julho', '17 de Julho', '18 de Julho', '19 de Julho', '19 de Julho', '22 de Julho', '22 de Julho'],
    subHeading4: ['22 de Julho', '23 de Julho', '23 de Julho', '24 de Julho', '25 de Julho', '25 de Julho', '25 de Julho'],
    subHeading5: ['26 de Julho', '27 de Julho', '27 de Julho', '29 de Julho', '31 de Julho', '31 de Julho', '31 de Julho'],
    blogDate: ['Carolina Maria', 'Daniel Leandro', 'Catarina Castelo', 'Diogo Castanho', 'Dante Varela', 'Rúben Bravo', 'Nuno Sousa', 'João Silva'],
    // tslint:disable-next-line:max-line-length
    blogDate2: ['Afonso Silva', 'Bernardo Silva', 'Andreia Sérgio', 'Ana Patrícia Guilherme', 'Afonso de Andrade Guerreiro', 'Sofia Pereira', 'Sofia Escrevente', 'Miguel Dias'],
    blogDate3: ['José Barroso', 'Salomé Amaral', 'Cristiana Amaral', 'João Vasco Alves', 'Cristiana Parreira', 'Mauro Rosário', 'Maria Aranha'],
    blogDate4: ['Hugo Brites', 'Luís Ferreira', 'João Galvão', 'João Matos', 'Inês Lidónio', 'Error', 'Error'],
    blogDate5: ['Rafael Sena', 'Edwin Freira', 'Isabel Nunes', 'Daniel Cardoso', 'Marta Silva', 'Miguel Menúria', 'Marisa Rodrigues'],
  },
  {
    id: 7,
    limit: 5,
    heading: 'August',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: ['assets/images/static-slider/profiles/user1.jpg', 'assets/images/static-slider/profiles/user5.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['1 de Agosto', '2 de Agosto', '2 de Agosto', '3 de Agosto', '6 de Agosto'],
    subHeading2: ['6 de Agosto', '7 de Agosto', '8 de Agosto', '8 de Agosto', '10 de Agosto'],
    subHeading3: ['10 de Agosto', '10 de Agosto', '10 de Agosto', '11 de Agosto', '11 de Agosto'],
    subHeading4: ['12 de Agosto', '15 de Agosto', '19 de Agosto', '20 de Agosto', '24 de Agosto'],
    subHeading5: ['26 de Agosto', '28 de Agosto'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Miguel Namorado de Carvalho', 'José Augusto Pedro Salvador', 'Error', 'Paulo Pina', 'Raquel Silva'],
    blogDate2: ['Telma Rodrigues', 'Vanessa Carvalho', 'Miguel Oliveira', 'Diogo Lúcio', 'Maria Inês Carvalho de Duarte'],
    blogDate3: ['Luigy Marques', 'Miguel Nascimento', 'Catarina Tomé', 'João Eduardo Figueiredo', 'Maria Carolina Neves'],
    blogDate4: ['Ana Catarina', 'Bruno Sousa', 'Pedro Pires', 'João Miguel Marques', 'João Silveirinha'],
    blogDate5: ['Bruno Alcobia', 'Cátia Barata'],
  },
  {
    id: 8,
    limit: 4,
    heading: 'September',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['1 de Setembro', '2 de Setembro', '2 de Setembro', '7 de Setembro'],
    subHeading2: ['8 de Setembro', '8 de Setembro', '9 de Setembro', '12 de Setembro'],
    subHeading3: ['12 de Setembro', '17 de Setembro', '18 de Setembro', '20 de Setembro'],
    subHeading4: ['23 de Setembro', '23 de Setembro', '24 de Setembro', '24 de Setembro'],
    subHeading5: ['29 de Setembro', '29 de Setembro', '29 de Setembro', '30 de Setembro'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Fabiana Batista', 'Ivo Rego', 'Leonor Fontes', 'Diogo Figueredo'],
    blogDate2: ['Vanessa Santos', 'Leonor Laranjeira', 'João Melão', 'Bernardo Pereira'],
    blogDate3: ['José Ferreira', 'Beatriz Gomes', 'Fátima Lopes (Catequista)', 'Fábio Tavares'],
    blogDate4: ['Cátia Lima Cordeiro', 'Leonardo Catarro', 'Diogo Fialho', 'Tomás Dias'],
    blogDate5: ['Daniel Montinho', 'Hugo Gonçalves', 'Sara Zózimo David', 'Marco Figueiredo'],
  },
  {
    id: 9,
    limit: 4,
    heading: 'October',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['2 de Outubro', '5 de Outubro', '5 de Outubro', '5 de Outubro'],
    subHeading2: ['6 de Outubro', '6 de Outubro', '6 de Outubro', '18 de Outubro'],
    subHeading3: ['18 de Outubro', '21 de Outubro', '25 de Outubro', '27 de Outubro'],
    subHeading4: ['28 de Outubro', '28 de Outubro', '28 de Outubro', '28 de Outubro'],
    subHeading5: ['29 de Outubro', '31 de Outubro', '31 de Outubro'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Vasco Crespo', 'Lucas Barrigó', 'Sasha Lacasta', 'Miguel Luís'],
    blogDate2: ['Sandra Nobre', 'Carolina Calado', 'Marisa Pereira', 'António Latas'],
    blogDate3: ['Miguel Tavares', 'Daniela Couto', 'Gonçalo Lobato', 'Fátima de Domingos Cota'],
    blogDate4: ['Teresa Guedes', 'Andreia Esteves', 'Márcia Fontes', 'José Gomes'],
    blogDate5: ['Madrinha Cristina', 'Franco Villanueva', 'Rodrigo Ferreira'],
  },
  {
    id: 10,
    limit: 5,
    heading: 'November',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user3.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['1 de Novembro', '2 de Novembro', '2 de Novembro', '2 de Novembro', '3 de Novembro'],
    subHeading2: ['4 de Novembro', '8 de Novembro', '8 de Novembro', '11 de Novembro', '11 de Novembro'],
    subHeading3: ['12 de Novembro', '12 de Novembro', '12 de Novembro', '13 de Novembro', '16 de Novembro'],
    subHeading4: ['18 de Novembro', '19 de Novembro', '22 de Novembro', '23 de Novembro', '23 de Novembro'],
    subHeading5: ['23 de Novembro', '26 de Novembro', '27 de Novembro', '29 de Novembro', '29 de Novembro'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Diogo Solipa', 'Maria Carolina', 'Diogo Tomás', 'Diogo Rafael', 'Natalie Mendes'],
    blogDate2: ['Pedro Afonso Tomé', 'Alex Garcia', 'Miguel Barreto', 'Gonçalo Correia', 'Hélder Bento'],
    blogDate3: ['Leonel Corado', 'Gonçalo Teixeira', 'Henrique Tomé', 'Fernando Prates', 'Maria Antónia Freire'],
    blogDate4: ['Alzira Santos', 'Daniel Soares', 'Bárbara Santos', 'João Ferreira', 'José Azevedo'],
    blogDate5: ['Beatriz Neves', 'João Vasconcelos', 'Mafalda Rosa', 'Rodrigo Vicente', 'Mariana Reis'],
  },
  {
    id: 11,
    limit: 5,
    heading: 'December',
    image: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user1.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image2: ['assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image3: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user3.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image4: ['assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user2.jpg',
    'assets/images/static-slider/profiles/user4.jpg',
    'assets/images/static-slider/profiles/user5.jpg',
    'assets/images/static-slider/profiles/user5.jpg'],
    image5: ['assets/images/static-slider/profiles/user4.jpg', 'assets/images/static-slider/profiles/user5.jpg'],
    // tslint:disable-next-line:max-line-length
    subHeading: ['4 de Dezembro', '5 de Dezembro', '6 de Dezembro', '7 de Dezembro', '10 de Dezembro'],
    subHeading2: ['12 de Dezembro', '16 de Dezembro', '17 de Dezembro', '17 de Dezembro', '18 de Dezembro'],
    subHeading3: ['19 de Dezembro', '19 de Dezembro', '21 de Dezembro', '21 de Dezembro', '21 de Dezembro'],
    subHeading4: ['22 de Dezembro', '24 de Dezembro', '27 de Dezembro', '28 de Dezembro', '28 de Dezembro'],
    subHeading5: ['30 de Dezembro', '31 de Dezembro'],
    // tslint:disable-next-line:max-line-length
    blogDate: ['Luana Nascimento', 'Francisco Rodrigues', 'Leonardo Santos', 'Miguel Mendes', 'Bruno Filipe'],
    blogDate2: ['Marcelo Feliz', 'Duarte Natalie', 'Beatriz Miranda', 'Maria de Fátima Salvador', 'Joana Vieira'],
    blogDate3: ['Rúben Eloio', 'Tio Juca', 'Ana Anjos', 'Sofia Anjos', 'Pedro Ferreira'],
    blogDate4: ['Jéssica Neves', 'Maria José Duarte Ribeiro', 'Duarte Anastácio', 'Nuno Casinhas', 'Jaime Oliveira'],
    blogDate5: ['Claúdia Dias', 'Diogo Pinto'],
  },
];


