
// @ts-ignore



export class RouteHGSS {
  id = 0;
  confirmL: boolean[] = [true, true];
  ListNames: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  ListImages: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  ListDescription: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  confirm: boolean[][] = [[true, true, true, true, true], [true, true, true, true, true]];
  confirmHacked: boolean[][] = [[true, true, true, true, true], [true, true, true, true, true]];
  confirmLevel: boolean[][] = [[true, true, true, true, true], [true, true, true, true, true]];
  confirmLevelHacked: boolean[][] = [[true, true, true, true, true], [true, true, true, true, true]];
  backgroundRate: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  backgroundRate2: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  backgroundLevelRate: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  backgroundLevelRate2: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  length$: number[][] = [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]];
  lengthHacked: number[][] = [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]];
  lengthLevel$: number[][] = [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]];
  lengthLevelHacked: number[][] = [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]];
  image = '';
  heading = '';
  // @ts-ignore
  subHeading = '';
  description = '';
  backgroundWildTitles: string[] = ['', '', '', '', ''];
  backgroundVersions: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  wildTitles: string[] = ['', '', '', '', ''];
  wildTitles2: string[] = ['', '', '', '', ''];
  encounterImages: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  encounters: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  especifications: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  especificationsImages: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  levels: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  levelsHacked: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  rates: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  rates2: string[][] = [['', '', '', '', ''], ['', '', '', '', '']];
  final = '';
  ItemTitles: string[] = ['', '', '', '', ''];
}


export let routeshgss: RouteHGSS[];

// @ts-ignore


routeshgss = [
  {
    id: 0,
    heading: 'New Bark Town',
    image: 'assets/images/Seal/New_Bark_Town_HGSS.png',
    confirmL: [true, true, false],
    subHeading: 'Items',
    description: 'Location',
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)',
      'Gift Pokémon',
      'Special Encounters (Hacked Version), ',
      'Surfing (Both Versions)',
      'Fishing (Both Versions) - Old Rod',
      'Fishing (Both Versions) - Good Rod',
      'Fishing (Both Versions) - Super Rod'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png'],
      ['//archives.bulbagarden.net/media/upload/5/59/072MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/073MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/5/59/072MS3.png',
    'https://archives.bulbagarden.net/media/upload/3/33/129MS3.png',
    'http://archives.bulbagarden.net/media/upload/e/e4/090MS3.png',
    'http://archives.bulbagarden.net/media/upload/c/c0/170MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/5/59/072MS3.png',
    'https://archives.bulbagarden.net/media/upload/3/33/129MS3.png',
    'http://archives.bulbagarden.net/media/upload/e/e4/090MS3.png',
    'http://archives.bulbagarden.net/media/upload/c/c0/170MS3.png'],
    ['http://archives.bulbagarden.net/media/upload/c/c0/170MS3.png',
    'https://archives.bulbagarden.net/media/upload/6/67/073MS3.png',
     'https://archives.bulbagarden.net/media/upload/e/e4/090MS3.png' ,
     'https://archives.bulbagarden.net/media/upload/c/c6/171MS3.png',
    'https://archives.bulbagarden.net/media/upload/f/fc/130MS3.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'],
      ['Chikorita', 'Cyndaquil', 'Totodile'],
      ['Rotom', 'Darkrai'],
      ['Tentacool', 'Tentacruel'],
      ['Tentacool', 'Magikarp', 'Shellder', 'Chinchou'],
      ['Tentacool', 'Magikarp', 'Shellder', 'Chinchou'],
      ['Chinchou', 'Tentacruel', 'Shellder', 'Lanturn', 'Gyarados']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png'],
    ['https://archives.bulbagarden.net/media/upload/7/7d/HGSS_Surf_M.png',
    'https://archives.bulbagarden.net/media/upload/7/7d/HGSS_Surf_M.png'],
    ['https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png'],
    ['https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png'],
  ['https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/b/b2/Bag_Old_Rod_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing'],
    ['Surf', 'Surf'],
    ['Fishing', 'Fishing', 'Fishing', 'Fishing'],
    ['Fishing', 'Fishing', 'Fishing', 'Fishing'],
    ['Fishing', 'Fishing', 'Fishing', 'Fishing', 'Fishing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3], [3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3, 3]],
    // tslint:disable-next-line:max-line-length
    confirmLevel: [[true, true, true], [true, true, true], [true, true], [true, true], [true, true, true, true], [true, true, true, true], [true, true, true, true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50'], ['10-25', '15-25'], ['10', '10', '10', '10'], ['20', '20', '20', '20'], ['40', '40', '40', '40', '40']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0], [0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0, 0]],
    // tslint:disable-next-line:max-line-length
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false], [false, false], [false, false, false, false], [false, false, false, false], [false, false, false, false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50'], ['10-25', '15-25'], ['10', '10', '10', '10'], ['20', '20', '20', '20'], ['40', '40', '40', '40', '40']],
    // tslint:disable-next-line:max-line-length
    confirm: [[true, true, true], [true, true, true], [true, true], [true, true], [true, true, false, false], [true, true, true, true], [true, true, true, true, false]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4], [4, 4], [4, 2, 0, 0], [4, 4, 2, 2], [4, 4, 2, 2, 0]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#c9d2d5', '#c9d2d5', '#1dc8cd', '#1dc8cd'],
      ['#c9d2d5', '#c9d2d5', '#c9d2d5', '#c9d2d5'],
      ['#c9d2d5', '#c9d2d5', '#c9d2d5', '#c9d2d5', '#1dc8cd']],
    // tslint:disable-next-line:max-line-length
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One'], ['90%', '10%'], ['5%', '95%', '', ''], ['60%', '30%', '3%', '7%'], ['60%', '7%', '30%', '3%', '']],
    // tslint:disable-next-line:max-line-length
    confirmHacked: [[false, false, false], [false, false, false], [false, false], [false, false], [false, true, true, true], [false, false, true, true], [false, false, true, true, true]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0], [0, 0], [0, 2, 4, 4], [0, 0, 2, 2], [0, 0, 2, 2, 4]], // doesnt do nothing
    backgroundRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff'],
      ['#c9d2d5', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#ffffff', '#ffffff', '#1dc8cd', '#1dc8cd'],
      ['#ffffff', '#ffffff', '#1dc8cd', '#1dc8cd', '#1dc8cd']],
    rates2: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One'], ['90%', '10%'], ['5%', '60%', '35%', '5%'], ['60%', '30%', '60%', '40%'], ['60%', '7%', '60%', '30%', '10%']],


    // tslint:disable-next-line:max-line-length


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 1,
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', '2'],
    confirmL: [true, true],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Route 29',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/5/5c/Johto_Route_29_HGSS.png/799px-Johto_Route_29_HGSS.png',
    subHeading: 'Items',
    description: 'Location',

    backgroundWildTitles: ['#33cc4a', '#91e8a0', '#086216', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)',
      'Wild Encounters - Both Versions (Morning/Day)',
      'Wild Encounters - Both Versions (Night)',
      'Special Pokémon'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff', '#75dcea', '#d3bc1a'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png',
    'https://www.serebii.net/pokedex-xy/icon/165.png',
    'https://www.serebii.net/pokedex-xy/icon/167.png'],
    ['https://www.serebii.net/pokedex-xy/icon/016.png',
    'https://www.serebii.net/pokedex-xy/icon/161.png',
    'https://www.serebii.net/pokedex-xy/icon/019.png',
    'https://www.serebii.net/pokedex-xy/icon/396.png',
    'https://www.serebii.net/pokedex-xy/icon/263.png',
    'https://www.serebii.net/pokedex-xy/icon/399.png',
    'https://www.serebii.net/pokedex-xy/icon/187.png',
    'https://www.serebii.net/pokedex-xy/icon/265.png'],
    ['http://archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    'https://www.serebii.net/pokedex-xy/icon/019.png',
    'https://www.serebii.net/pokedex-xy/icon/261.png',
    'https://www.serebii.net/pokedex-xy/icon/263.png',
    'https://www.serebii.net/pokedex-xy/icon/399.png',
    'https://www.serebii.net/pokedex-xy/icon/265.png'],
    ['https://www.serebii.net/pokedex-swsh/icon/403.png',
    'https://www.serebii.net/pokedex-swsh/icon/312.png',
    'https://www.serebii.net/pokedex-swsh/icon/311.png',
    'https://www.serebii.net/pokedex-swsh/icon/162.png',
    'https://www.serebii.net/pokedex-swsh/icon/020.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco', 'Ledyba', 'Spinarak'],
      ['Pidgey', 'Sentret', 'Rattata', 'Starly', 'Zigzagoon', 'Bidoof', 'Hoppip', 'Wurmple'],
      ['Hoothoot', 'Rattata', 'Poochyena', 'Zigzagoon', 'Bidoof', 'Wurmple'],
      ['Shinx', 'Minun', 'Plusle', 'Furret', 'Raticate'], [''], [''], [''], ['']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png']],
    especifications: [['Tree', 'Tree', 'Tree', 'Tree', 'Tree'],
    ['Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass'],
    ['Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass'],
    ['Grass', 'Grass', 'Grass', 'Grass', 'Grass']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#c9d2d5', '#c9d2d5', '#c9d2d5'],
      ['#c9d2d5', '#c9d2d5'],
      ['#b5e0f3', '#e8783f', '#e8783f']],
    lengthLevel$: [[3, 3, 3, 3, 3], [1, 1, 1, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0], [3, 1, 1, 0, 0]],
    // tslint:disable-next-line:max-line-length
    confirmLevel: [[true, true, true, true, true],
      [true, true, true, false, false, false, false, false],
      [true, true, false, false, false, false],
      [true, true, true, false, false]],
    levels: [['2-3', '2-3', '2-3', '4-5', '4-5'], ['2-4', '2-4', '2-4'], ['2-4', '2-4'], ['2-3', '2-3', '2-3', '2-4', '2-4']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#edfad9', '#edfad9', '#be6eec', '#be6eec']],
    lengthLevelHacked:  [[0, 0, 0, 0, 0], [2, 2, 2, 3, 3, 3, 3, 3], [2, 2, 3, 3, 3, 3], [3, 2, 2, 3, 3, 3]],
    // tslint:disable-next-line:max-line-length
    confirmLevelHacked: [[false, false, false, false, false],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true],
      [false, true, true, true, true]],
    // tslint:disable-next-line:max-line-length
    levelsHacked: [['', '', '', '', ''],
      ['3-5', '3-5', '3-5', '3-5', '3-5', '3-5', '3-5', '3-5'],
      ['3-5', '3-5', '3-5', '3-5', '3-5', '3-5'],
      ['3-5', '3-5', '3-5', '3-5', '3-5']],
    // tslint:disable-next-line:max-line-length
    confirm: [[true, true, true, true, true],
      [true, true, true, false, false, false, false, false],
      [true, true, false, false, false, false],
      [true, true, true, false, false]],
    length$: [[4, 4, 4, 4, 4], [2, 2, 2, 0, 0, 0, 0, 0], [2, 2, 0, 0, 0, 0], [4, 2, 2, 0, 0]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#c9d2d5', '#c9d2d5', '#c9d2d5'],
      ['#c9d2d5', '#c9d2d5'],
      ['#b5e0f3', '#e8783f', '#e8783f']],
    rates: [['20%', '50%', '10%', '20%', '20%'], ['55%', '40%', '5%'], ['85%', '15%'], ['40%', '20%', '20%', '', '']],
    // tslint:disable-next-line:max-line-length
    confirmHacked: [[false, false, false, false, false],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true],
      [false, true, true, true, true]],
    lengthHacked: [[0, 0, 0, 0, 0], [2, 2, 2, 4, 4, 4, 4, 4], [2, 2, 4, 4, 4, 4], [0, 2, 2, 4, 4]], // doesnt do nothing
    backgroundRate2: [['', '', ''],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#edfad9', '#edfad9', '#be6eec', '#be6eec']],
    rates2: [['', '', '', '', ''], ['20%', '20%', '15%', '15%', '10%', '10%', '5%', '5%'], ['20%', '20%', '15%', '15%', '15%', '15%'], ['', '50%', '50%', '50%', '50%']],
   final: 'White background means that it can be found on the version(s) indicated above.\n ' +
    'Gold and Blue background means that it can be found on the specific colored versions of the normal game.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.\n' +
    'Pastoral Sounds are represented by their green natural Pastoral color while the Meridian Sound is represented by a purple color.\n' +
    'Hoenn sound is represented by a orange color while a light-blue represents Sinnoh Sounds.',


  },
  {
    id: 2,
    confirmL: [true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Route 46',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/e/e4/Johto_Route_46_HGSS.png/452px-Johto_Route_46_HGSS.png',
    subHeading: 'Items',
    description: 'Location',

    backgroundWildTitles: ['#33cc4a', '#91e8a0', '#086216', '#c02086', '#fab9e4'],
    wildTitles: ['Headbutt (Normal Versions)',
      'Wild Encounters - Both Versions (Morning/Day)',
      'Wild Encounters - Both Versions (Night)',
      'Special Pokémon - Normal Versions',
      'Special Pokémon - Hacked Versions'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff', '#75dcea', '#d3bc1a'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff', '#ffffff', '#ffffff']],
    encounterImages: [['https://www.serebii.net/pokedex-xy/icon/021.png',
    'https://www.serebii.net/pokedex-xy/icon/214.png',
    'https://www.serebii.net/pokedex-xy/icon/190.png'],
    ['https://www.serebii.net/pokedex-xy/icon/074.png',
    'https://www.serebii.net/pokedex-xy/icon/021.png',
    'https://www.serebii.net/pokedex-xy/icon/019.png',
    'https://www.serebii.net/pokedex-xy/icon/325.png',
    'https://www.serebii.net/pokedex-xy/icon/333.png',
    'https://www.serebii.net/pokedex-xy/icon/322.png',
    'https://www.serebii.net/pokedex-xy/icon/231.png',
    'https://www.serebii.net/pokedex-xy/icon/039.png'],
    ['https://www.serebii.net/pokedex-xy/icon/074.png',
    'https://www.serebii.net/pokedex-xy/icon/019.png',
    'https://www.serebii.net/pokedex-xy/icon/322.png',
    'https://www.serebii.net/pokedex-xy/icon/325.png',
    'https://www.serebii.net/pokedex-xy/icon/035.png',
    'https://www.serebii.net/pokedex-swsh/icon/403.png',
    'https://www.serebii.net/pokedex-xy/icon/228.png',
    'https://www.serebii.net/pokedex-xy/icon/039.png'],
    ['https://www.serebii.net/pokedex-swsh/icon/403.png',
    'https://www.serebii.net/pokedex-swsh/icon/312.png',
    'https://www.serebii.net/pokedex-swsh/icon/311.png'],
    ['https://www.serebii.net/pokedex-xy/icon/075.png',
    'https://www.serebii.net/pokedex-xy/icon/022.png',
    'https://www.serebii.net/pokedex-xy/icon/174.png']],
    encounters: [['Spearow', 'Heracross', 'Aipom'],
      ['Geodude', 'Spearow', 'Rattata', 'Spoink', 'Swablu', 'Numel', 'Phanpy', 'Jigglypuff'],
      ['Geodude', 'Rattata', 'Numel', 'Spoink', 'Clefairy',  'Shinx', 'Houndour', 'Jigglypuff'],
      ['Shinx', 'Minun', 'Plusle'],
      ['Graveler', 'Fearow', 'Igglybuff'], [''], [''], ['']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png'],
    ['//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png',
    '//archives.bulbagarden.net/media/upload/3/32/HGSS_Grass.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass'],
    ['Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass'],
    ['Grass', 'Grass', 'Grass'], ['Grass', 'Grass', 'Grass']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#c9d2d5', '#c9d2d5', '#c9d2d5'],
      ['#c9d2d5', '#c9d2d5'],
      ['#b5e0f3', '#e8783f', '#e8783f'],
      ['#b5e0f3', '#e8783f', '#EDFAD9']],
    lengthLevel$: [[3, 3, 3, 3, 3], [1, 1, 1, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0], [3, 3, 3], [0, 0, 0]],
    // tslint:disable-next-line:max-line-length
    confirmLevel: [[true, true, true, false, false],
      [true, true, true, false, false, false, false, false],
      [true, true, false, false, false, false, false, false],
      [true, true, true, false, false],
      [false, false, false, false, false]],
    levels: [['2-8', '2-5', '3-8'], ['2-3', '2-3', '2-4'], ['2-4', '2-4'], ['2-3', '2-3', '2-3', '2-4', '2-4'], ['2-3', '2-3', '2-3']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#BE6EEC', '#BE6EEC', '#EDFAD9']],
    lengthLevelHacked:  [[0, 0, 0, 0, 0], [2, 2, 2, 3, 3, 3, 3, 3], [2, 2, 3, 3, 3, 3, 3, 3], [3, 0, 0], [3, 3, 3]],
    // tslint:disable-next-line:max-line-length
    confirmLevelHacked: [[false, false, false, false, false],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [false, false, false, true, true],
      [true, true, true, true, true]],
    // tslint:disable-next-line:max-line-length
    levelsHacked: [['', '', '', '', ''],
      ['4-6', '4-6', '4-6', '4-6', '4-6', '4-6', '4-6', '4-6'],
      ['4-6', '4-6', '4-6', '4-6', '4-6', '4-6', '4-6', '4-6'],
      ['3-5', '3-5', '3-5'],
      ['3-5', '3-5', '3-5']],
    // tslint:disable-next-line:max-line-length
    confirm: [[true, true, true, true, true],
      [true, true, true, false, false, false, false, false],
      [true, true, false, false, false, false, false, false],
      [true, true, true, false, false],
      [false, false, false, false, false]],
    length$: [[4, 4, 4, 4, 4], [2, 2, 2, 0, 0, 0, 0, 0], [2, 2, 0, 0, 0, 0, 0, 0], [4, 4, 4, 0, 0], [0, 0, 0]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#c9d2d5', '#c9d2d5', '#c9d2d5'],
      ['#c9d2d5', '#c9d2d5'],
      ['#b5e0f3', '#e8783f', '#e8783f'],
      ['#b5e0f3', '#e8783f', '#e8783f']],
    rates: [['50%', '30%', '20%'], ['40%', '35%', '25%'], ['45%', '55%'], ['40%', '20%', '20%', '', ''], ['40%', '20%', '20%', '', '']],
    // tslint:disable-next-line:max-line-length
    confirmHacked: [[false, false, false, false, false],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [false, false, false],
      [true, true, true]],
    lengthHacked: [[0, 0, 0, 0, 0], [2, 2, 2, 4, 4, 4, 4, 4], [2, 2, 4, 4, 4, 4, 4, 4], [0, 0, 0, 4, 4], [4, 4, 4]], // doesnt do nothing
    backgroundRate2: [['', '', ''],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd', '#1dc8cd'],
      ['#BE6EEC', '#BE6EEC', '#EDFAD9']],
    rates2: [['', '', '', '', ''], ['20%', '20%', '10%', '10%', '10%', '10%', '10%', '10%'], ['20%', '10%', '20%', '10%', '10%', '10%', '10%', '10%'], ['', '50%', '50%'], ['50%', '50%', '50%']],

    final: 'White background means that it can be found on the version(s) indicated above.\n ' +
    'Gold and Blue background means that it can be found on the specific colored versions of the normal game.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.\n' +
    'Pastoral Sounds are represented by their green natural Pastoral color while the Meridian Sound is represented by a purple color.\n' +
    'Hoenn sound is represented by a orange color while a light-blue represents Sinnoh Sounds.',

  },
  {
    id: 3,
    confirmL: [true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Cherrygroove City',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/b/bb/Cherrygrove_City_HGSS.png/800px-Cherrygrove_City_HGSS.png',
    subHeading: 'Items',
    description: 'Location',
    backgroundWildTitles: ['#33cc4a'],
    wildTitles: ['Headbutt (Normal Versions)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/0/0e/204MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    'https://www.serebii.net/pokedex-xy/icon/276.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Pineco', 'Hoothoot', 'Exeggcute',  'Taillow'],
      ['Chikorita', 'Cyndaquil', 'Totodile'],
      ['Rotom', 'Darkrai'], ['']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree', 'Tree']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 1, 0], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true, false], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3', ''], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#8a7e4e', '#8a7e4e'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 2, 3], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, true, true], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '18-20', '18-25'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true, false], [true, true, true], [true, true]],
    length$: [[4, 4, 2, 0], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['30%', '50%', '20%', ''], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, true, true], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 2, 4], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['#ffffff', '#ffffff', '#8a7e4e', '#8a7e4e'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates2: [['30%', '50%', '65%', '35%'], [], []],
    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 4,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Route 30',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/a/a9/Johto_Route_30_HGSS.png/282px-Johto_Route_30_HGSS.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 5,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Route 31',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/d/d8/Johto_Route_31_HGSS.png/800px-Johto_Route_31_HGSS.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 6,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Dark Cave (Route 31 Side)',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/4/4e/Dark_Cave_1_HGSS.png/784px-Dark_Cave_1_HGSS.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 7,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Violet City',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/5/55/Violet_City_HGSS.png/533px-Violet_City_HGSS.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 8,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Sprout Tower',
    image: 'https://archives.bulbagarden.net/media/upload/c/cd/HGSS_Sprout_Tower-Night.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 9,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Route 32',
    image: 'https://archives.bulbagarden.net/media/upload/thumb/8/86/Johto_Route_32_HGSS.png/147px-Johto_Route_32_HGSS.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],


    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
  {
    id: 10,
    confirmL: [true, true, true],
    ItemTitles: ['Item (Both Versions)', 'Item (Hacked Versions)', ''],
    ListNames: [['Potion x5', 'Potion', 'Pokégear', 'Everstone', 'Master Ball', 'S.S.Ticket'],
                ['Running Shoes', 'Bicycle', 'GBA Sounds'], ['', '', '']],
    ListImages: [['//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/e/ed/Bag_Potion_Sprite.png',
    '//archives.bulbagarden.net/media/upload/f/f3/Pok%C3%A9gear_Icon.png',
    '//archives.bulbagarden.net/media/upload/0/0d/Bag_Everstone_Sprite.png',
    '//archives.bulbagarden.net/media/upload/6/6d/Bag_Master_Ball_Sprite.png',
    '//archives.bulbagarden.net/media/upload/8/80/Bag_S.S._Ticket_Sprite.png'],
    ['https://pokemon3d.net/wiki/images/0/0e/Running_Shoes_big.png',
    'https://archives.bulbagarden.net/media/upload/d/d8/Bag_Bicycle_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/3/34/Bag_GB_Sounds_Sprite.png'], ['', '', '']],
    ListDescription: [['Gift from Professor Elm\'s aide after getting a starter Pokémon',
    'Where Silver was standing (hidden)',
    'Given by Mom after getting a starter Pokémon',
    'Gift from Professor Elm if shown the Mystery Egg Togepi',
    'Gift from Professor Elm after earning the eight Johto Badges',
    'Gift from Professor Elm after entering the Hall of Fame'],
    ['Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon',
    'Given by Mom before getting a starter Pokémon'], ['', '', '']],
    heading: 'Ruins of Alph',
    image: 'https://archives.bulbagarden.net/media/upload/f/f8/HGSS_Ruins_of_Alph-Night.png',
    subHeading: 'Items',
    description: 'Location',


    backgroundWildTitles: ['#33cc4a', '#d0ce54', '#c02086'],
    wildTitles: ['Headbutt (Normal Versions)', 'Gift Pokémon', 'Special Encounters (Hacked Version)'],
    wildTitles2: ['Pokémon', 'Specification', 'Levels', 'Rate'],
    backgroundVersions: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    encounterImages: [['//archives.bulbagarden.net/media/upload/b/bd/102MS3.png',
    '//archives.bulbagarden.net/media/upload/6/67/163MS3.png',
    '//archives.bulbagarden.net/media/upload/0/0e/204MS3.png'],
    ['https://archives.bulbagarden.net/media/upload/9/90/152MS3.png',
    'https://archives.bulbagarden.net/media/upload/8/8e/155MS3.png',
    'https://archives.bulbagarden.net/media/upload/4/48/158MS3.png'],
    ['https://img.pokemondb.net/sprites/sword-shield/normal/rotom.png',
    'https://archives.bulbagarden.net/media/upload/d/d4/491MS6.png']],
    encounters: [['Exeggcute', 'Hoothoot', 'Pineco'], ['Chikorita', 'Cyndaquil', 'Totodile'], ['Rotom', 'Darkrai']],
    // tslint:disable-next-line:max-line-length
    especificationsImages: [['https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png',
    'https://archives.bulbagarden.net/media/upload/thumb/a/a3/HGSS_Headbutt_Johto.png/20px-HGSS_Headbutt_Johto.png'],
    ['https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png',
    'https://archives.bulbagarden.net/media/upload/a/ad/Elm_OD.png'],
    ['https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png',
    'https://archives.bulbagarden.net/media/upload/5/55/Bag_Premier_Ball_Sprite.png']],
    especifications: [['Tree', 'Tree', 'Tree'],
    ['Starter Pokemon', 'Starter Pokemon', 'Starter Pokemon'],
    ['After Plain Badge', 'After obtaining all badges and Lunar Wing']],
    backgroundLevelRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevel$: [[3, 3, 3], [3, 3, 3], [3, 3]],
    confirmLevel: [[true, true, true], [true, true, true], [true, true]],
    levels: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    backgroundLevelRate2: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    lengthLevelHacked:  [[0, 0, 0], [0, 0, 0], [0, 0]],
    confirmLevelHacked: [[false, false, false], [false, false, false], [false, false]],
    levelsHacked: [['2-3', '2-3', '2-3'], ['5', '5', '5'], ['20', '50']],
    confirm: [[true, true, true], [true, true, true], [true, true]],
    length$: [[4, 4, 4], [4, 4, 4], [4, 4]],
    backgroundRate: [['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff', '#ffffff'],
      ['#ffffff', '#ffffff']],
    rates: [['20%', '50%', '30%'], ['One', 'One', 'One'], ['One', 'One']],
    confirmHacked: [[false, false, false], [false, false, false], [false, false]],
    lengthHacked: [[0, 0, 0], [0, 0, 0], [0, 0]], // doesnt do nothing
    backgroundRate2: [['', '', ''], ['', '', ''], ['', '']],
    rates2: [[], [], []],
    final: 'White background means that it can be found on the version(s) indicated above.\n' +
    'Grey background means that it can be found on the normal version while white-blue background means that it can be found on the hacked version.',


  },
];
